# Docs: https://github.com/Azure/webapps-deploy

name: Build and deploy React Vite app to Azure Web App - app-clinicapp-web-66020565

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Build React Vite app
        working-directory: ./web
        env:
          VITE_API_BASE: https://app-clinicapp-api-66020565-bkdhd8amdtbxazar.southeastasia-01.azurewebsites.net/
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: web/dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: ./dist

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_164CB79D5BDF4E77A82D1B2FA60CE779 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F9D33016E85B4A7FB99FE406B8A8124D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_47EAC12CB63A4FC386500A277B537592 }}

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-clinicapp-web-66020565'
          slot-name: 'Production'
          package: ./dist
